Created CRUD for News,Like and Feedback Services and Add pagination News and Feedback
Capstone-Tim-15/e-complaint-be pull request #28
Opened 2023-11-29 18:45 UTC by rootsyahdan

endpoint is
/users/news      -----> POST and GET
/users/news/search?title=    ------> GET 
/users/news/search?id= ------> GET  

/users/news/feedback/search?news_id=   ------>  GET  
/users/news/feedback/search?id= ------>  GET
/users/news -----> post and get

/admin/news -----> POST and GET
/admin/news/{id} ------> PUT and DELETE
/admin/news/search?title=     ------>  GET  
/admin/news/search?id=      ------>  GET  

/admin/news/feedback  -----> POST and GET
/admin/news/feedback/{id} ------> PUT and DELETE
/admin/news/feedback/search?news_id=     ------>  GET  
/admin/news/feedback/search?id=           ------>  GET  

/like  -----> POST and GET
/like/search/id=         -----> GET
/like/:id      --------->PUT and DELETE

2023-11-30 12:21 UTC, hafidznaufl requested changes
Ada beberapa hal yg ga sesuai sama branch develop original dan seharusnya gausah dicommit atau bisa dimasukin `.gitignore` yaitu:

- folder `.idea` beserta isinya
- file `DS_Store` di folder `config` dan `schema`

beberapa penamaan file yg kurang sesuai sama branch `develop` dan harus dilakukan penyesuaian dengan cara yaitu : 

- ganti nama semua file yg ada di folder `request` dengan contoh : 
contoh : `feedbackRequestConvert` --> `feedbackConvertRequest` dst.


selain diatas semua udh oke dari gua, thank you.

2023-12-01 07:49 UTC, InnakaDylee requested changes
- Pada news endpoint users/news jangan ada POST
- Pada feedback endpoint users/news tolong ditambahkan /feedback?news_id=?
- Pada fitur create ( POST ) feedback pakai queryparam agar ada relasi feedback ke news
- Pada fitur create ( POST ) feedback pakai extract token agar ada identitas siapa yang memberikan feedback
- Pada fitur create ( POST ) feedback ditambahkan column fullname agar ada nama dari usernya (extract token)

2023-12-01 07:49 UTC, hafidznaufl approved these changes

2023-12-01 14:40 UTC, InnakaDylee approved these changes

2023-12-01 14:41 UTC, merged